server:
  port: 8081

spring:
  cloud:
    stream:
      function:
        definition: playGame;gameSquareCreated
      bindings:
        playGame-in-0:
          destination: game-played
          group: pyl
        gameSquareCreated-out-0:
          destination: square-created