server:
  port: 8080

logging:
  level:
    io:
      r2dbc:
        h2: TRACE

spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

  r2dbc:
    url: r2dbc:h2:mem:///DBNAME?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  cloud:
    stream:
      function:
        definition: playGame;acceptGameSquare
      bindings:
        playGame-out-0:
          destination: game-played
        acceptGameSquare-in-0:
          destination: square-created
          group: groupTest